#define FOLLOWER_CARRIER_THREEGX 1
#define FOLLOWER_CARRIER_ENABLE_LOGGING 0
#define FOLLOWER_CARRIER_ENABLE_CUTSCENE_FAST_FORWARD 0
#define FOLLOWER_CARRIER_PIPELINE_BLOOM_ENABLE_OFFSET 0x03e0
#define FOLLOWER_CARRIER_PIPELINE_DOF_ENABLE_OFFSET 0x0d2c
#define FOLLOWER_CARRIER_PIPELINE_SKYBOX_DRAW_MANAGER_OFFSET 0x0154
#define FOLLOWER_CARRIER_PIPELINE_SKYBOX_CONTAINER_OFFSET 0x015c
#define FOLLOWER_CARRIER_PIPELINE_WEATHER_CONTAINER_OFFSET 0x0264
#define FOLLOWER_CARRIER_PIPELINE_EFFECT_GROUP_LIST_OFFSET 0x0ba8
#define FOLLOWER_POKEMON_USE_TRAIL_POLICY 1

#define FollowerCarrier_InitializeRuntime FollowerCarrier_InitializeRuntimeUltra
#define FollowerCarrier_ShutdownRuntime FollowerCarrier_ShutdownRuntimeUltra
#define FollowerCarrier_Update FollowerCarrier_UpdateUltra
#define FollowerCarrier_Terminate FollowerCarrier_TerminateUltra
#define FollowerCarrier_HostTerminate FollowerCarrier_HostTerminateUltra
#define FollowerCarrier_SuspendForWaterRide FollowerCarrier_SuspendForWaterRideUltra
#define FollowerCarrier_OpenPc FollowerCarrier_OpenPcUltra
#define FollowerCarrier_IsFreeField FollowerCarrier_IsFreeFieldUltra
#define FollowerCarrier_AfterEventCheck FollowerCarrier_AfterEventCheckUltra
#define FollowerCarrier_GetNetworkState FollowerCarrier_GetNetworkStateUltra
#define FollowerCarrier_ConfigureRemoteReplicas FollowerCarrier_ConfigureRemoteReplicasUltra
#define FollowerCarrier_SetRemoteReplicaState FollowerCarrier_SetRemoteReplicaStateUltra
#define FollowerCarrier_GetRemoteReplicaDiagnostics FollowerCarrier_GetRemoteReplicaDiagnosticsUltra

#include "gameplay/FieldRuntimeBridge.inl"
