#define FollowerCarrier_ShouldEraseEdgeMaterial FollowerCarrier_ShouldEraseEdgeMaterialRegular
#define FOLLOWER_CARRIER_THREEGX 1
#define FOLLOWER_CARRIER_ENABLE_LOGGING FOLLOWER_3GX_DIAGNOSTIC
#define FOLLOWER_CARRIER_ENABLE_CUTSCENE_FAST_FORWARD 0
#define FOLLOWER_CARRIER_PIPELINE_EDGE_NORMAL_OFFSET 0x0ce0
#define FOLLOWER_CARRIER_PIPELINE_BLOOM_ENABLE_OFFSET 0x03b0
#define FOLLOWER_CARRIER_PIPELINE_DOF_ENABLE_OFFSET 0x0cfc
#define FOLLOWER_CARRIER_PIPELINE_SKYBOX_DRAW_MANAGER_OFFSET 0x0124
#define FOLLOWER_CARRIER_PIPELINE_SKYBOX_CONTAINER_OFFSET 0x012c
#define FOLLOWER_CARRIER_PIPELINE_WEATHER_CONTAINER_OFFSET 0x0234
#define FOLLOWER_CARRIER_PIPELINE_EFFECT_GROUP_LIST_OFFSET 0x0b78
#define FOLLOWER_CARRIER_SAVEDATA_EVENT_WORK_OFFSET 0x1590
#define FOLLOWER_POKEMON_EVENT_WORK_SPRAY_COUNT_OFFSET 0x09dc
#define FOLLOWER_POKEMON_USE_TRAIL_POLICY 1
#define FOLLOWER_POKEMON_RELEASE_INDEPENDENT_HEAP_FOR_FIELD_EVENTS 1

#define FollowerCarrier_InitializeRuntime FollowerCarrier_InitializeRuntimeRegular
#define FollowerCarrier_ShutdownRuntime FollowerCarrier_ShutdownRuntimeRegular
#define FollowerCarrier_Update FollowerCarrier_UpdateRegular
#define FollowerCarrier_Terminate FollowerCarrier_TerminateRegular
#define FollowerCarrier_HostTerminate FollowerCarrier_HostTerminateRegular
#define FollowerCarrier_SuspendForWaterRide FollowerCarrier_SuspendForWaterRideRegular
#define FollowerCarrier_OpenPc FollowerCarrier_OpenPcRegular
#define FollowerCarrier_IsFreeField FollowerCarrier_IsFreeFieldRegular
#define FollowerCarrier_AfterEventCheck FollowerCarrier_AfterEventCheckRegular
#define FollowerCarrier_GetNetworkState FollowerCarrier_GetNetworkStateRegular
#define FollowerCarrier_ConfigureRemoteReplicas FollowerCarrier_ConfigureRemoteReplicasRegular
#define FollowerCarrier_SetRemoteReplicaState FollowerCarrier_SetRemoteReplicaStateRegular
#define FollowerCarrier_GetRemoteReplicaDiagnostics FollowerCarrier_GetRemoteReplicaDiagnosticsRegular

#include "gameplay/FieldRuntimeBridge.inl"
